version: "3.9"
services:
  dovecot:
    image: marooou/postfix-roundcube
    environment:
      - ADMIN_USERNAME=root
      - ADMIN_PASSWD=L3tm31n
      - DOMAIN_NAME=example.com
      - USERS=user1:Pass11,user2:Pass22
    ports:
    - 25:25
    - 80:80
    - 110:110
    - 143:143
    - 465:465
    - 993:993
    - 995:995
